version: "1.25"

volumes:
  audios:
  mosquitto.conf:

services:
  bot:
    build: bot/.
    container_name: bot
    volumes:
      - audios:/home/bot/audios_telegram
    network_mode: host
    

  voice-assistant:
    build: voice_assistant/.
    container_name: voice-assistant
    volumes:
      - audios:/home/voice_assistant/audios_foxie
    network_mode: host

  broker:
    image: "eclipse-mosquitto"
    container_name: mosquitto
    network_mode: host
    restart: always
    volumes:
      - mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    ports:
      - "1883:1883"
      - "9000:9000"

